// Desktop "paste invite link to join" (#297). The desktop app is the web frontend bundled at a
// local origin, so it has no address bar — the only way to consume a web invite link is to paste it.
// We reuse the SAME shareable web links (no separate desktop invite scheme):
//   • /join/<code>      — private-channel invite link generated by JoinLink.tsx (redeem → join as member)
//   • /c/<slug>[?t=…]   — a channel share link (open the channel directly)
// Parsing is pure + host-allowlisted so a bad/hostile paste is rejected with a clear error, never acted on.
import { isAllowlistedServerOrigin } from "./desktopPairing";
import { normalizeServerOrigin } from "./serverProfiles";

export type ParsedInviteLink =
  | { kind: "join"; serverOrigin: string; code: string }
  | { kind: "channel"; serverOrigin: string; slug: string; token: string | null };

const JOIN_PATH = /^\/join\/([A-Za-z0-9_-]{1,128})\/?$/;
const CHANNEL_PATH = /^\/c\/([a-z0-9][a-z0-9-]*)\/?$/;

// Parse a pasted string into a structured invite link, or null if it is not a well-formed invite
// URL from an allowlisted server. `allowedOrigins` is the set of server origins the desktop trusts
// (its official + custom server profiles). Whitespace and a trailing slash are tolerated; anything
// else that doesn't match exactly — wrong host, junk, smuggled query params, credentials — is rejected.
export function parsePastedInviteLink(input: string, allowedOrigins: readonly string[]): ParsedInviteLink | null {
  let url: URL;
  try {
    url = new URL(input.trim());
  } catch {
    return null;
  }
  if (url.protocol !== "https:" && url.protocol !== "http:") return null;
  if (url.username || url.password || url.hash) return null;
  if (!isAllowlistedServerOrigin(url.origin, allowedOrigins)) return null;

  const joinMatch = url.pathname.match(JOIN_PATH);
  if (joinMatch !== null) {
    // An invite code carries all authority in itself — reject any query string so a paste can't smuggle
    // a second parameter (e.g. a token) past validation.
    if (url.search !== "") return null;
    return { kind: "join", serverOrigin: url.origin, code: joinMatch[1]! };
  }

  const channelMatch = url.pathname.match(CHANNEL_PATH);
  if (channelMatch !== null) {
    for (const key of url.searchParams.keys()) {
      if (key !== "t") return null; // only the share token param is allowed on a channel link
    }
    const rawToken = url.searchParams.get("t");
    if (rawToken !== null && rawToken === "") return null; // ?t= with an empty value is malformed
    return { kind: "channel", serverOrigin: url.origin, slug: channelMatch[1]!, token: rawToken };
  }

  return null;
}

export type InviteJoinResult =
  | { status: "navigate"; slug: string }
  | { status: "wrong-server"; serverOrigin: string }
  | { status: "error"; message: string };

export interface ResolveInviteContext {
  activeOrigin: string;
  token: string;
  redeem: (token: string, code: string) => Promise<{ channel_slug: string; joined: boolean }>;
}

// Bridge a parsed invite into the current desktop session. The desktop session is authenticated
// per-server (one paired credential per origin), so an invite for a different server can't be
// redeemed with this session's token — we surface `wrong-server` instead of silently failing.
// For a join link we redeem it (reusing the web /api/join/<code> endpoint) with the desktop's own
// access token; for a channel link the user is already authed for this origin, so we just open it.
export async function resolvePastedInvite(
  parsed: ParsedInviteLink,
  ctx: ResolveInviteContext,
): Promise<InviteJoinResult> {
  const active = normalizeServerOrigin(ctx.activeOrigin);
  const target = normalizeServerOrigin(parsed.serverOrigin);
  if (active === null || target === null || active !== target) {
    return { status: "wrong-server", serverOrigin: parsed.serverOrigin };
  }
  if (parsed.kind === "channel") {
    return { status: "navigate", slug: parsed.slug };
  }
  try {
    const redeemed = await ctx.redeem(ctx.token, parsed.code);
    return { status: "navigate", slug: redeemed.channel_slug };
  } catch (cause) {
    return { status: "error", message: cause instanceof Error ? cause.message : "failed to join" };
  }
}
