// party capture — durable scribe tags for important channel messages.
import type { CaptureKind, CaptureRecord } from "../rest";
import { isHelpArg, parseArgs, str, unknownFlagError, valueFlagError } from "../args";
import { resolveChannel } from "../config";
import { jsonFrame } from "../json";
import { resolveAuth } from "../oidc-cli";
import { createCapture, handleRestError, listCaptures } from "../rest";
import { isSlug, parseNonNegativeIntFlag, parsePositiveIntFlag } from "../validation";

const CAPTURE_KINDS: readonly string[] = ["decision", "requirement", "bug", "action-item"] satisfies CaptureKind[];
const FLAGS = ["channel", "as", "kind", "message", "note", "since", "limit", "json", "issue-body"];
const HELP = `usage:
  party capture <seq> [channel|--channel C] --as decision|requirement|bug|action-item [-m note] [--json] [--issue-body]
  party capture list [channel|--channel C] [--as kind] [--since seq] [--limit n] [--json] [--issue-body]

Create or list durable captures for decisions, requirements, bugs, and action items.
--issue-body prints a GitHub-ready issue body; it does not create a public issue.`;

function parseKind(value: string | undefined): CaptureKind | null {
  return value !== undefined && CAPTURE_KINDS.includes(value) ? (value as CaptureKind) : null;
}

function compact(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

function formatCapture(c: CaptureRecord): string {
  const note = c.note ? ` · ${c.note}` : "";
  return `#${c.seq} ${c.capture_kind} ${c.message.sender.name}: ${compact(c.message.body).slice(0, 180)}${note}`;
}

function issueTitle(captures: CaptureRecord[]): string {
  const first = captures[0];
  if (!first) return "Captured AgentParty notes";
  const label = captures.length === 1 ? first.capture_kind : "captured notes";
  return `[AgentParty] ${label} from #${first.channel}`;
}

function issueBody(captures: CaptureRecord[]): string {
  const lines = [
    `## ${issueTitle(captures)}`,
    "",
    "Generated by `party capture --issue-body`. Review before creating a public issue.",
    "",
  ];
  for (const c of captures) {
    lines.push(`### ${c.capture_kind}: #${c.seq}`);
    lines.push("");
    lines.push(`- Channel: \`${c.channel}\``);
    lines.push(`- Message: \`#${c.seq}\` by \`${c.message.sender.name}\` (${c.message.sender.kind})`);
    lines.push(`- Captured by: \`${c.created_by}\` (${c.created_by_kind})`);
    if (c.note) lines.push(`- Note: ${c.note}`);
    lines.push("");
    lines.push("```");
    lines.push(c.message.body);
    lines.push("```");
    lines.push("");
  }
  return lines.join("\n");
}

export async function run(argv: string[]): Promise<number> {
  if (isHelpArg(argv, { allowHelpPositional: true })) {
    console.log(HELP);
    return 0;
  }
  const { positionals, flags } = parseArgs(argv, { booleans: ["json", "issue-body"], aliases: { m: "message" } });
  const cfg = await resolveAuth();
  if (!cfg) {
    console.error("no config, run: party login or party init --server URL --token T");
    return 1;
  }
  const unknown = unknownFlagError(flags, FLAGS);
  if (unknown !== null) {
    console.error(unknown);
    return 1;
  }
  const flagError = valueFlagError(flags, ["channel", "as", "kind", "message", "note", "since", "limit"]);
  if (flagError !== null) {
    console.error(flagError);
    return 1;
  }
  const channel = resolveChannel(str(flags.channel) ?? (positionals[0] === "list" ? positionals[1] : positionals[1]));
  if (!channel) {
    console.error("no channel, pass one or bind with: party init --channel C");
    return 1;
  }
  if (!isSlug(channel)) {
    console.error("channel must match [a-z0-9][a-z0-9-]{0,63}");
    return 1;
  }
  const kind = parseKind(str(flags.as) ?? str(flags.kind));
  if ((str(flags.as) ?? str(flags.kind)) !== undefined && kind === null) {
    console.error("--as must be decision|requirement|bug|action-item");
    return 1;
  }

  if (positionals[0] === "list") {
    const since = parseNonNegativeIntFlag(str(flags.since), "since");
    if (typeof since === "string") {
      console.error(since);
      return 1;
    }
    const limit = parsePositiveIntFlag(str(flags.limit), "limit", 1000);
    if (typeof limit === "string") {
      console.error(limit);
      return 1;
    }
    try {
      const captures = await listCaptures(cfg.server, cfg.token, channel, {
        ...(kind !== null ? { kind } : {}),
        since: since ?? 0,
        limit: limit ?? 100,
      });
      if (flags["issue-body"] === true) console.log(issueBody(captures));
      else for (const c of captures) console.log(flags.json === true ? JSON.stringify(jsonFrame(c as unknown as Record<string, unknown>)) : formatCapture(c));
      return 0;
    } catch (e) {
      return handleRestError(e);
    }
  }

  const seq = Number(positionals[0]);
  if (!Number.isInteger(seq) || seq <= 0) {
    console.error("seq must be a positive integer");
    return 1;
  }
  if (kind === null) {
    console.error("--as is required: decision|requirement|bug|action-item");
    return 1;
  }
  const note = str(flags.message) ?? str(flags.note);
  try {
    const capture = await createCapture(cfg.server, cfg.token, channel, {
      seq,
      kind,
      ...(note !== undefined ? { note } : {}),
    });
    if (flags["issue-body"] === true) console.log(issueBody([capture]));
    else console.log(flags.json === true ? JSON.stringify(jsonFrame(capture as unknown as Record<string, unknown>)) : `captured ${formatCapture(capture)}`);
    return 0;
  } catch (e) {
    return handleRestError(e);
  }
}
