import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const read = (path: string) => readFileSync(resolve(root, path), "utf8");

describe("Claude Cross-session discovery docs", () => {
  test("documents the marketplace shell without merging it into the private bridge", () => {
    const architecture = read("docs/session-bridge-architecture.html");
    expect(architecture).toContain('id="marketplace-plugin"');
    expect(architecture).toContain("一个运行时，两层插件外壳");
    expect(architecture).toContain("plugins/agentparty/");
    expect(architecture).toContain("mcp__plugin_&lt;plugin&gt;_&lt;server&gt;__...");
    expect(architecture).toContain("mcp__agentparty-channel__...");
    expect(architecture).toContain("session_output_limit_exceeded");
    expect(architecture).toContain("verify-agentparty-plugin-install.ts");
    expect(architecture).toContain("installed_disabled_by_default=true");
    expect(architecture).toContain("cached_bundle_exact=true");
    expect(architecture).toContain("channel_declared=true");
    expect(architecture).toContain("lifecycle_hooks_present=true");
    expect(architecture).toContain("standard_hooks_autoload_safe=true");
    expect(architecture).toContain("claude_mcp_manifest_visible=true");
    expect(architecture).toContain("party doctor claude-plugin --channel C --json");
    expect(architecture).toContain("party claude --verify --channel C");
    expect(architecture).toContain("busy_activity_observed_before_send=true");
    expect(architecture).toContain("claim_accept_reply_chain_observed=true");
    expect(architecture).toContain("delivery_terminal_settled=true");
    expect(architecture).toContain("<code>model_calls_started</code> 写成 true");
    expect(architecture).toContain("source_cleanup=not_needed|retracted|not_found_or_unconfirmed|failed");
    expect(architecture).toContain("cleanup_required=true");
    expect(architecture).toContain("cleanup_search_marker");
    expect(architecture).toContain("PermissionRequest");
    expect(architecture).toContain("不上传 prompt 或工具参数");
    expect(architecture).toContain("channel.topology_visibility=observed|not_observed|unavailable");
    expect(architecture).toContain("Marketplace Plugin ≥ 2.1.154");
    expect(architecture).toContain("--claude-package-version X.Y.Z");
    expect(architecture).toContain("claude_version_matches_request=true");
    expect(architecture).toContain("worker-deploy.yml");
    expect(architecture).toContain("40 位 commit SHA");
    expect(architecture).toContain("version + commit");
    expect(architecture).toContain("deployed_at");
    expect(architecture).toContain("busy_activity_not_observed");
    expect(architecture).toContain("directed_delivery v1 + delivery_recovery v1");
    expect(architecture).toContain("party claude &lt;channel&gt;");
    expect(architecture).toContain("一次性环境 opt-in");
    expect(architecture).toContain("stop_hook_active=true");
    expect(architecture).toContain("被阻止的 Stop 会保持 <code>working</code>");
    expect(architecture).toContain("<code>lifecycle</code> 对象");
    expect(architecture).toContain("<code>model_calls_started=false</code>");
    expect(architecture).toContain("8 MiB");
    expect(architecture).toContain("1 MiB");
    expect(architecture).toContain("8192");
    expect(architecture).toContain("短探针另有每流 1 MiB 上限");
    for (const path of ["README.md", "README.zh.md"]) {
      const source = read(path);
      expect(source).toContain("claude plugin marketplace add leeguooooo/AgentParty");
      expect(source).toContain("claude plugin install agentparty@agentparty");
      expect(source).toContain("claude plugin enable agentparty@agentparty");
      expect(source).toContain("party claude <channel>");
      expect(source).toContain("identity_not_agent");
      expect(source).toContain("activity_not_observed");
      expect(source).toContain("channel.topology_visibility");
      expect(source).toContain("topology_not_observed");
      expect(source).toContain("topology_unavailable");
      expect(source).toContain("2.1.154");
      expect(source).toContain("defaultEnabled");
      expect(source).toContain("--claude-package-version 2.1.154");
      expect(source).toContain("claude_version_matches_request=true");
      expect(source).toContain("worker-deploy.yml");
      expect(source).toContain(path === "README.md" ? "40-character" : "40 位 commit SHA");
      expect(source).toContain("version + commit");
      expect(source).toContain("deployed_at");
      expect(source).toContain(path === "README.md" ? "no-model preflight" : "无模型预检");
      expect(source).toContain(path === "README.md" ? "Codex shell" : "Codex 外壳");
      expect(source).toContain("bun scripts/verify-agentparty-plugin-install.ts");
      expect(source).toContain("party doctor claude-plugin --channel <channel> --json");
      expect(source).toContain("party claude --verify --channel dev");
      expect(source).toContain("busy_activity_observed_before_send");
      expect(source).toContain("claim_accept_reply_chain_observed");
      expect(source).toContain("delivery_terminal_settled");
      expect(source).toContain("system/init");
      expect(source).toContain("`unknown`");
      expect(source).toContain("source_cleanup=not_needed|retracted|not_found_or_unconfirmed|failed");
      expect(source).toContain("cleanup_required=true");
      expect(source).toContain("cleanup_search_marker");
      expect(source).toContain("PermissionRequest");
      expect(source).toContain("current_task");
      expect(source).toContain(path === "README.md" ? "never prompt text or tool arguments" : "不上传 prompt 或工具参数");
      expect(source).toContain(path === "README.md" ? "multiple matches fail closed" : "多条则 fail closed");
      expect(source).toContain("busy_activity_not_observed");
      expect(source).toContain("delivery_recovery v1");
      expect(source).toContain("channel_writes_started=false");
      expect(source).toContain("`--live`");
      expect(source).toContain(path === "README.md"
        ? "If Stop is blocked for an unfinished linked reply, presence stays `working`"
        : "Stop 因待回复 execution 被阻止时，presence 保持 `working`");
      expect(source).toContain("plugin_lifecycle_unavailable");
      expect(source).toContain("`lifecycle`");
      expect(source).toContain(path === "README.md" ? "random attempt ID" : "随机 attempt ID");
    }
    const online = read("web/public/docs/index.html");
    expect(online).toContain("Marketplace plugin：安装 Skill、Hook 与 Channel");
    expect(online).toContain("claude plugin marketplace add leeguooooo/AgentParty");
    expect(online).toContain("party claude &lt;channel&gt;");
    expect(online).toContain("identity_not_agent");
    expect(online).toContain("activity_not_observed");
    expect(online).toContain("channel.topology_visibility");
    expect(online).toContain("topology_not_observed");
    expect(online).toContain("topology_unavailable");
    expect(online).toContain("2.1.154+");
    expect(online).toContain("defaultEnabled");
    expect(online).toContain("--claude-package-version X.Y.Z");
    expect(online).toContain("claude_version_matches_request=true");
    expect(online).toContain("worker-deploy.yml");
    expect(online).toContain("40-character commit SHA");
    expect(online).toContain("version + commit");
    expect(online).toContain("deployed_at");
    expect(online).toContain("启动前的无模型预检");
    expect(online).toContain("续跑后的 Stop 必须放行");
    expect(online).toContain("被阻止的 Stop 保持 <code>working</code>");
    expect(online).toContain("bun scripts/verify-agentparty-plugin-install.ts");
    expect(online).toContain("party doctor claude-plugin --channel &lt;channel&gt; --json");
    expect(online).toContain("party claude --verify --channel dev");
    expect(online).toContain("busy_activity_observed_before_send");
    expect(online).toContain("delivery_terminal_settled");
    expect(online).toContain("stream initialization is <code>unknown</code>");
    expect(online).toContain("source_cleanup=not_needed|retracted|not_found_or_unconfirmed|failed");
    expect(online).toContain("cleanup_required=true");
    expect(online).toContain("cleanup_search_marker");
    expect(online).toContain("PermissionRequest");
    expect(online).toContain("never prompt text or tool arguments");
    expect(online).toContain("multiple exact sender/body matches fail closed");
    expect(online).toContain("busy_activity_not_observed");
    expect(online).toContain("registers no delivery adapter");
    expect(online).toContain("<code>channel_writes_started</code>");
    expect(online).toContain("<code>--live</code>");
    expect(online).toContain("CLAUDE_CONFIG_DIR");
    expect(online).toContain("不能证明登录、MCP 连通或消息送达");
    expect(online).toContain("每个输出流限制在 1 MiB");
    expect(online).toContain("<code>lifecycle</code> 对象");
    expect(online).toContain("随机 attempt ID");
  });

  test("keeps native acceptance synchronized by the observed send result", () => {
    const source = read("scripts/verify-claude-cross-session.ts");
    expect(source).toContain("createClaudeSendMessageResultBarrier");
    expect(source).toContain("AGENTPARTY_CROSS_SESSION_NATIVE_RELEASE_FILE");
    expect(source).toContain("timingBarrierIntact");
    expect(source).toContain("receiver_wait_boundary_before_marker");
    expect(source).toContain("sender_send_message_result_observed");
    expect(source).toContain("--preflight-only");
    expect(source).toContain("agentparty.claude-cross-session-native-preflight.v1");
    expect(source).toContain("model_calls_started: false");
    expect(source).toContain("delivery_verified: false");
    expect(source).toContain('"invalid_arguments"');
    expect(source).toContain('"invalid_request"');
    expect(source).toContain('"internal_error"');
    expect(source).toContain('failure_phase: "evidence"');
    expect(source).toContain("delivery_verified: passed");
    expect(source).toContain("receiver_startup_failed");
    expect(source).not.toContain("sleep 20");
  });

  test("keeps the launch path discoverable from both READMEs", () => {
    for (const path of ["README.md", "README.zh.md"]) {
      const source = read(path);
      expect(source).toContain("party bridge claude design-review");
      expect(source).toContain("--cross-session required");
      expect(source).toContain("--cross-session-inbound accept");
      expect(source).toContain("docs/session-bridge-architecture.html");
      expect(source).toContain("AGENTPARTY_CONFIG");
      expect(source).toContain("cross_session=enabled_for_launch");
      expect(source).toContain("cross_session=channel_only");
      expect(source).toContain("party_channel_peer_check");
      expect(source).toContain("SessionStart");
      expect(source).toContain("candidate_ref");
      expect(source).toContain("v3");
      expect(source).toContain("--check --json");
      expect(source).toContain("party bridge claude --verify");
      expect(source).toContain("--receiver-cwd");
      expect(source).toContain("--sender-cwd");
      expect(source).toContain("expected_topology_relation");
      expect(source).toContain("session_start_armed");
      expect(source).toContain("delivery_verified");
      expect(source).toContain("claude auth status");
      expect(source).toContain("system/init.session_id");
      expect(source).toContain("850 ms");
      expect(source).toContain("send_to");
      expect(source).toContain("1–64");
      expect(source).toContain("mcp__agentparty-channel__");
      expect(source).toContain("isolatePeerMachines");
      expect(source).toContain("cross_machine=approval_required");
      expect(source).toContain("cross_machine_policy_on_launch");
      expect(source).toContain("on another machine (Remote Control)");
      expect(source).toContain("in the cloud");
      expect(source).toContain("lookalike");
      expect(source).toContain("unsupported_provider");
      expect(source).toContain("feature_flag_evaluation_disabled");
      expect(source).toContain("DISABLE_TELEMETRY");
      expect(source).toContain("claude_api_provider");
      expect(source).toContain("cross_session_conflict_variables");
      expect(source).toContain("channel_probe_phase");
      expect(source).toContain("channel_probe_attempts");
      expect(source).toContain("runtime_probe_attempts");
      expect(source).toContain("`blockers`");
      expect(source).toContain("worker_upgrade_required");
      expect(source).toContain("150/500 ms");
      expect(source).toContain("capability probe");
      expect(source).toContain(path === "README.md" ? "malformed decoration" : "异常装饰");
      expect(source).toContain(path === "README.md" ? "ambient environment" : "全局环境");
      expect(source).toContain(path === "README.md" ? "text-only main-session" : "纯文本主会话");
      expect(source).toContain("tool_result");
      expect(source).toContain("session_id");
      expect(source).toContain(path === "README.md" ? "duplicate marker" : "重复 marker");
      expect(source).toContain(path === "README.md" ? "each outbound tool chain" : "每条出站工具链");
      expect(source).toContain(path === "README.md" ? "distinct reply marker" : "reply marker");
      expect(source).toContain(path === "README.md" ? "private 0600 signal file" : "0600 信号文件");
      expect(source).toContain("timing_barriers_intact=true");
      expect(source).toContain("distinct_claude_session_ids=true");
      expect(source).toContain("distinct_bridge_addresses=true");
      expect(source).toContain(path === "README.md" ? "non-error `SendMessage` result" : "非错误且唯一的");
      expect(source).toContain(path === "README.md" ? "wait result before" : "等待结果必须早于");
      expect(source).toContain(path === "README.md" ? "share one 180-second deadline" : "同一个 180 秒总时限");
      expect(source).toContain(path === "README.md" ? "one 20-second readiness" : "同一个 20 秒 readiness");
      expect(source).toContain(path === "README.md" ? "full stream" : "完整流");
      expect(source).toContain(path === "README.md" ? "direct, top-level, singleton" : "顶层、直接且单独");
      expect(source).toContain(path === "README.md" ? "only non-error result" : "唯一且非错误");
      expect(source).toContain(path === "README.md" ? "foreign or child session" : "外来 session 或子 agent");
      expect(source).toContain(path === "README.md" ? "no unrelated tool call" : "不能插入无关工具");
      expect(source).toContain(path === "README.md" ? "non-null `agent_id`" : "非空 `agent_id`");
      expect(source).toContain("`parent_tool_use_id`");
      expect(source).toContain("`isReplay`");
      expect(source).toContain(path === "README.md" ? "blocking exit 2" : "退出码 2");
      expect(source).toContain(path === "README.md" ? "malformed envelopes" : "畸形 envelope");
      expect(source).toContain(path === "README.md" ? "two distinct confirmed" : "两个不同的 confirmed");
      expect(source).toContain(path === "README.md" ? "4,096 nodes" : "4096 个节点");
      expect(source).toContain("4 MiB");
      expect(source).toContain("tool_use_id");
      expect(source).toContain(path === "README.md" ? "previous session cannot" : "上一条 session");
      expect(source).toContain(path === "README.md" ? "share the consume lock" : "共用 consume lock");
      expect(source).toContain("`blockers`");
      expect(source).toContain("claude_auth_status");
      expect(source).toContain("claude_auth_required");
      expect(source).toContain("worker_upgrade_required");
      expect(source).toContain("runtime_peer_unavailable");
      expect(source).toContain("agentparty_unavailable");
      expect(source).toContain("receiver_identity");
      expect(source).toContain("sender_channel_access");
      expect(source).toContain("not_checked");
      expect(source).toContain("invalid_request");
      expect(source).toContain("environment_unavailable");
      expect(source).toContain("internal_error");
      expect(source).toContain("`error_code`");
      expect(source).toContain("AGENTPARTY_RUNTIME_SMOKE_TOKEN");
      expect(source).toContain("caller_binding=live_socket");
      expect(source).toContain("--capability-only");
      expect(source).toContain("sockets_closed=true");
      expect(source).toContain(path === "README.md" ? "sends no Channel or Claude message" : "不发送 Channel 或 Claude 消息");
      expect(source).toContain("protocol_checked=false");
      expect(source).toContain(path === "README.md" ? "10-second" : "10 秒截止时间");
      expect(source).toContain("worker_deployment_status");
      expect(source).toContain("worker_deployment_unavailable");
      expect(source).toContain("development_unversioned");
      expect(source).toContain("agentparty.claude-cross-session-native-preflight.v1");
      expect(source).toContain("model_calls_started=false");
      expect(source).toContain("receiver_lifecycle_activity_observed=true");
      expect(source).toContain("sender_lifecycle_activity_observed=true");
      expect(source).toContain(path === "README.md" ? "native delivery" : "原生送达");
      expect(source).toContain("error_code=invalid_arguments");
      expect(source).toContain("internal_error");
      expect(source).toContain("request|preflight|receiver_startup|execution|evidence|internal");
      expect(source).toContain("delivery_verified=true");
      expect(source).toContain("party who --json");
      expect(source).toContain("same_local_installation");
      expect(source).toContain("same_node");
      expect(source).toContain("cross_session=session_start_unarmed");
      expect(source).toContain(path === "README.md" ? "while Claude is still running" : "Claude 仍运行");
      expect(source).toContain(path === "README.md" ? "all three signals" : "三项未齐");
      expect(source).toContain(path === "README.md"
        ? "full AgentParty verifier uses its v2 acceptance schema"
        : "AgentParty 完整验收对所有非 help 结果都使用 v2 acceptance schema");
    }
  });

  test("keeps the online guide and command table linked to the same safe path", () => {
    const source = read("web/public/docs/index.html");
    expect(source).toContain('href="#claude-cross-session"');
    expect(source).toContain('<section id="claude-cross-session">');
    expect(source).toContain("party bridge claude design-review");
    expect(source).toContain("party_channel_peers");
    expect(source).toContain("party_channel_peer_check");
    expect(source).toContain("SessionStart");
    expect(source).toContain("candidate_ref");
    expect(source).toContain("ListAgents");
    expect(source).toContain("same_local_installation");
    expect(source).toContain("same_node");
    expect(source).toContain("not proof of a physical computer");
    expect(source).toContain("cross_session=enabled_for_launch");
    expect(source).toContain("cross_session=channel_only");
    expect(source).toContain("at most five seconds");
    expect(source).toContain("v3");
    expect(source).toContain("--check --json");
    expect(source).toContain("peer_presence_checked=false");
    expect(source).toContain("claude_auth_unavailable");
    expect(source).toContain("receiver_session_start_armed=true");
    expect(source).toContain("cross_session=session_start_unarmed");
    expect(source).toContain("while Claude is still running");
    expect(source).toContain("arm receipt matching that address");
    expect(source).toContain("stdout empty");
    expect(source).toContain("--cross-session-inbound accept");
    expect(source).toContain("0/100/350/850 ms");
    expect(source).toContain("confirmed <code>send_to</code>");
    expect(source).toContain("1–64");
    expect(source).toContain("mcp__agentparty-channel__");
    expect(source).toContain("isolatePeerMachines");
    expect(source).toContain("cross_machine=approval_required");
    expect(source).toContain("cross_machine_policy_on_launch");
    expect(source).toContain("--receiver-cwd");
    expect(source).toContain("--sender-cwd");
    expect(source).toContain("expected_topology_relation");
    expect(source).toContain("on another machine (Remote Control)");
    expect(source).toContain("in the cloud");
    expect(source).toContain("lookalike");
    expect(source).toContain("unsupported_provider");
    expect(source).toContain("feature_flag_evaluation_disabled");
    expect(source).toContain("DISABLE_TELEMETRY");
    expect(source).toContain("claude_api_provider");
    expect(source).toContain("cross_session_conflict_variables");
    expect(source).toContain("channel_probe_phase");
    expect(source).toContain("channel_probe_attempts");
    expect(source).toContain("runtime_probe_attempts");
    expect(source).toContain("<code>blockers</code>");
    expect(source).toContain("party bridge claude --verify");
    expect(source).toContain("worker_upgrade_required");
    expect(source).toContain("150/500 ms");
    expect(source).toContain("capability probe");
    expect(source).toContain("AGENTPARTY_RUNTIME_SMOKE_TOKEN");
    expect(source).toContain("caller_binding=live_socket");
    expect(source).toContain("--capability-only");
    expect(source).toContain("sockets_closed=true");
    expect(source).toContain("不发送 Channel 或 Claude 消息");
    expect(source).toContain("protocol_checked=false");
    expect(source).toContain("10 秒截止时间");
    expect(source).toContain("worker_deployment_status");
    expect(source).toContain("worker_deployment_unavailable");
    expect(source).toContain("development_unversioned");
    expect(source).toContain("异常装饰");
    expect(source).toContain("全局环境");
    expect(source).toContain("纯文本主会话");
    expect(source).toContain("tool_result");
    expect(source).toContain("session_id");
    expect(source).toContain("重复 marker");
    expect(source).toContain("每条出站工具链");
    expect(source).toContain("true round trip");
    expect(source).toContain("no fixed sleep heuristic");
    expect(source).toContain("timing_barriers_intact=true");
    expect(source).toContain("two distinct <code>system/init.session_id</code>");
    expect(source).toContain("unique non-error <code>SendMessage</code> result");
    expect(source).toContain("receiver wait result precedes the first marker");
    expect(source).toContain("Both bridge exits share one 180-second deadline");
    expect(source).toContain("one 20-second readiness deadline");
    expect(source).toContain("receiver_lifecycle_activity_observed=true");
    expect(source).toContain("sender_lifecycle_activity_observed=true");
    expect(source).toContain("full stream");
    expect(source).toContain("direct, top-level, singleton");
    expect(source).toContain("完整流中该 tool-use ID 唯一");
    expect(source).toContain("only non-error, direct singleton result");
    expect(source).toContain("不能插入无关工具");
    expect(source).toContain("non-null <code>agent_id</code>");
    expect(source).toContain("non-null <code>agent_id</code> or <code>parent_tool_use_id</code>");
    expect(source).toContain("malformed <code>isReplay</code>");
    expect(source).toContain("blocking exit 2");
    expect(source).toContain("JSON scalars, arrays, empty objects");
    expect(source).toContain("two distinct confirmed results");
    expect(source).toContain("4,096 nodes");
    expect(source).toContain("4 MiB");
    expect(source).toContain("tool_use_id");
    expect(source).toContain("previous session cannot");
    expect(source).toContain("share the consume lock");
    expect(source).toContain("every independently known Marketplace lifecycle, authentication, provider, feature-flag, and runtime blocker");
    expect(source).toContain("claude_auth_status");
    expect(source).toContain("探针不可用");
    expect(source).toContain("agentparty_unavailable");
    expect(source).toContain("receiver 与 sender 的身份和频道访问分开报告");
  });

  test("keeps CLI help and the machine contract aligned", () => {
    const cli = read("cli/src/index.ts");
    const hook = read("cli/src/commands/hook.ts");
    const skill = read("skills/agentparty/SKILL.md");
    for (const source of [cli, skill]) {
      expect(source).toContain("--cross-session auto|off|required");
      expect(source).toContain("--cross-session-inbound accept|hold|refuse");
      expect(source).toContain("--check");
    }
    expect(cli).toContain("presence uplink remains launcher/serve-scoped");
    expect(cli).not.toContain("install makes any session visible");
    expect(hook).toContain("Claude sessions remain local-only");
    expect(hook).not.toContain("任何在此生效范围内的 Claude Code session");
    expect(skill).toContain("party_channel_peers");
    expect(skill).toContain("party_channel_peer_check");
    expect(skill).toContain("isolatePeerMachines");
    expect(skill).toContain("cross_machine=approval_required");
    expect(skill).toContain("cross_machine_policy_on_launch");
    expect(skill).toContain("--receiver-cwd");
    expect(skill).toContain("--sender-cwd");
    expect(skill).toContain("expected_topology_relation");
    expect(skill).toContain("on another machine (Remote Control)");
    expect(skill).toContain("in the cloud");
    expect(skill).toContain("claude_api_provider");
    expect(skill).toContain("cross_session_conflict_variables");
    expect(skill).toContain("channel_probe_phase");
    expect(skill).toContain("channel_probe_attempts");
    expect(skill).toContain("runtime_probe_attempts");
    expect(skill).toContain("`blockers`");
    expect(skill).toContain("party bridge claude --verify");
    expect(skill).toContain("party claude --verify --channel <slug>");
    expect(skill).toContain("claim_accept_reply_chain_observed");
    expect(skill).toContain("delivery_terminal_settled");
    expect(skill).toContain("spawned launcher without conclusive stream initialization is `unknown`");
    expect(skill).toContain("source_cleanup=not_needed|retracted|not_found_or_unconfirmed|failed");
    expect(skill).toContain("cleanup_required=true");
    expect(skill).toContain("cleanup_search_marker");
    expect(skill).toContain("PermissionRequest");
    expect(skill).toContain("never prompt text or tool arguments");
    expect(skill).toContain("channel.topology_visibility");
    expect(skill).toContain("topology_not_observed");
    expect(skill).toContain("topology_unavailable");
    expect(skill).toContain("2.1.154+");
    expect(skill).toContain("--claude-package-version X.Y.Z");
    expect(skill).toContain("claude_version_matches_request=true");
    expect(skill).toContain("worker-deploy.yml");
    expect(skill).toContain("40-character SHA");
    expect(skill).toContain("version + commit");
    expect(skill).toContain("deployed_at");
    expect(skill).toContain("fail closed on multiple matches");
    expect(skill).toContain("busy_activity_not_observed");
    expect(skill).toContain("delivery_recovery v1");
    expect(skill).toContain("channel_writes_started=false");
    expect(skill).toContain("`--live`");
    expect(skill).toContain("worker_upgrade_required");
    expect(skill).toContain("150/500 ms");
    expect(skill).toContain("capability probe");
    expect(skill).toContain("SessionStart");
    expect(skill).toContain("availability=confirmed");
    expect(skill).toContain("exactly one fresh exact-name match");
    expect(skill).toContain("not physical-host");
    expect(skill).toContain("launch readiness, not registration or delivery proof");
    expect(skill).toContain("session_start_armed=false");
    expect(skill).toContain("claude auth status");
    expect(skill).toContain("sender_session_start_armed=true");
    expect(skill).toContain("unsupported_provider");
    expect(skill).toContain("feature_flag_evaluation_disabled");
    expect(skill).toContain("DISABLE_TELEMETRY");
    expect(skill).toContain("private 0600 receipt file");
    expect(skill).toContain("--cross-session-inbound accept|hold|refuse");
    expect(skill).toContain("0/100/350/850 ms");
    expect(skill).toContain("confirmed result's `send_to`");
    expect(skill).toContain("1–64");
    expect(skill).toContain("mcp__agentparty-channel__");
    expect(skill).toContain("lookalike");
    expect(skill).toContain("Malformed");
    expect(skill).toContain("ambient environment");
    expect(skill).toContain("text-only main-session");
    expect(skill).toContain("tool_result");
    expect(skill).toContain("session_id");
    expect(skill).toContain("duplicate marker");
    expect(skill).toContain("each outbound tool chain");
    expect(skill).toContain("true round trip");
    expect(skill).toContain("verifier-private 0600 signal file");
    expect(skill).toContain("timing_barriers_intact=true");
    expect(skill).toContain("distinct_claude_session_ids=true");
    expect(skill).toContain("distinct_bridge_addresses=true");
    expect(skill).toContain("unique, non-error `SendMessage`");
    expect(skill).toContain("receiver wait result before the first inbound marker");
    expect(skill).toContain("one shared 180-second deadline");
    expect(skill).toContain("one shared 20-second");
    expect(skill).toContain("receiver_lifecycle_activity_observed=true");
    expect(skill).toContain("sender_lifecycle_activity_observed=true");
    expect(skill).toContain("full stream");
    expect(skill).toContain("direct, top-level, singleton");
    expect(skill).toContain("only non-error result");
    expect(skill).toContain("foreign or child session");
    expect(skill).toContain("no unrelated tool between steps");
    expect(skill).toContain("non-null `agent_id`");
    expect(skill).toContain("`parent_tool_use_id`");
    expect(skill).toContain("malformed `isReplay`");
    expect(skill).toContain("blocking exit 2");
    expect(skill).toContain("malformed envelopes");
    expect(skill).toContain("capped at 4 MiB");
    expect(skill).toContain("documented `tool_use_id`");
    expect(skill).toContain("two distinct confirmed results");
    expect(skill).toContain("4,096 nodes");
    expect(skill).toContain("events from the previous");
    expect(skill).toContain("share the consume lock");
    expect(skill).toContain("additive `blockers` array");
    expect(skill).toContain("claude_auth_status=logged_out");
    expect(skill).toContain("agentparty_unavailable");
    expect(skill).toContain("not collapse into endpoint-unavailable or raw `FAIL` text");
    expect(skill).toContain("`invalid_request`");
    expect(skill).toContain("`environment_unavailable`");
    expect(skill).toContain("`internal_error`");
    expect(skill).toContain("AGENTPARTY_RUNTIME_SMOKE_TOKEN");
    expect(skill).toContain("caller must be bound as `live_socket`");
    expect(skill).toContain("relation `same_local_installation`");
    expect(skill).toContain("reports `sockets_closed=true` only after both");
    expect(skill).toContain("bounded close handshakes and sends no");
    expect(skill).toContain("Channel or Claude message");
    expect(skill).toContain("`--capability-only`");
    expect(skill).toContain("protocol_checked=false");
    expect(skill).toContain("10-second deadline");
    expect(skill).toContain("worker_deployment_status=confirmed");
    expect(skill).toContain("worker_deployment_unavailable");
    expect(skill).toContain("development_unversioned");
    expect(skill).toContain("agentparty.claude-cross-session-native-preflight.v1");
    expect(skill).toContain("model_calls_started=false");
    expect(skill).toContain("never Claude registration, native delivery");
    expect(skill).toContain("error_code=invalid_arguments");
    expect(skill).toContain("before either Claude probe");
    expect(skill).toContain("failure_phase=request|preflight|receiver_startup|execution|evidence|internal");
    expect(skill).toContain("Raw receiver/execution diagnostics belong only");
    expect(skill).toContain("full AgentParty verifier must use its v2 acceptance schema");
    expect(skill).toContain("complete bidirectional gated chain");
    expect(skill).toContain("party who --json");
    expect(skill).toContain("never emits the stronger-sounding `same_node`");
    expect(skill).toContain("cross_session=session_start_unarmed");
    expect(skill).toContain("while Claude is still running");
    expect(skill).toContain("before all three signals arrive");
  });

  test("separates native Claude transport proof from AgentParty topology proof", () => {
    const source = read("docs/session-bridge-architecture.html");
    expect(source).toContain("channel_probe_phase");
    expect(source).toContain("channel_probe_attempts");
    expect(source).toContain("runtime_probe_attempts");
    expect(source).toContain("150/500 ms");
    expect(source).toContain("capability probe");
    expect(source).toContain("runtime smoke agent token");
    expect(source).toContain("全局环境");
    expect(source).toContain("纯文本主会话");
    expect(source).toContain("tool_result");
    expect(source).toContain("session_id");
    expect(source).toContain("重复 marker");
    expect(source).toContain("sender 唯一 <code>system/init</code>");
    expect(source).toContain("完整流计数");
    expect(source).toContain("完整流中该 tool-use ID 唯一且非错误");
    expect(source).toContain("同 ID 的重复 result");
    expect(source).toContain("顶层、直接且单独");
    expect(source).toContain("步骤之间不能插入无关工具");
    expect(source).toContain("非空 <code>agent_id</code>");
    expect(source).toContain("<code>parent_tool_use_id</code> 非空的子 agent");
    expect(source).toContain("不是严格布尔值的 <code>isReplay</code>");
    expect(source).toContain("退出码 2");
    expect(source).toContain("Hook 输入 envelope");
    expect(source).toContain("Hook stdin 资源上限");
    expect(source).toContain("工具调用关联");
    expect(source).toContain("https://code.claude.com/docs/en/hooks");
    expect(source).toContain("工具结果歧义");
    expect(source).toContain("工具结果资源上限");
    expect(source).toContain("会话重武装");
    expect(source).toContain("三个入口均在持锁时重查");
    expect(source).toContain("<code>blockers</code> 数组");
    expect(source).toContain("<code>claude_auth_status</code>");
    expect(source).toContain("<code>claude_api_provider</code>");
    expect(source).toContain("<code>agentparty_unavailable</code>");
    expect(source).toContain("<code>receiver_identity</code>");
    expect(source).toContain("另一枚 reply marker");
    expect(source).toContain("信号文件只协调时序");
    expect(source).toContain("timing_barriers_intact=true");
    expect(source).toContain("distinct_claude_session_ids=true");
    expect(source).toContain("distinct_bridge_addresses=true");
    expect(source).toContain("非错误且唯一的");
    expect(source).toContain("receiver 的等待结果早于首个 marker");
    expect(source).toContain("同一个 180 秒总时限");
    expect(source).toContain("同一个 20 秒 readiness 时限");
    expect(source).toContain("cross_session=session_start_unarmed");
    expect(source).toContain("Claude 仍运行时");
    expect(source).toContain("三项未齐");
    expect(source).toContain("same_local_installation");
    expect(source).toContain("same_node");
    const nativeStart = source.indexOf("Claude 原生 Cross-session 传输的真实验收入口");
    const integratedStart = source.indexOf("AgentParty 全链路验收入口");
    expect(nativeStart).toBeGreaterThanOrEqual(0);
    expect(integratedStart).toBeGreaterThan(nativeStart);
    const native = source.slice(nativeStart, integratedStart);
    expect(native).toContain("它不证明 AgentParty 的 topology");
    expect(native).toContain("没有 <code>candidate_ref</code>");
    expect(native).toContain("同一个 60 秒总时限");
    expect(native).toContain("15 秒 readiness 时限");
    expect(native).toContain("两个不同的唯一 <code>system/init.session_id</code>");
    expect(native).toContain("唯一、非错误的直接 result");
    expect(native).toContain("不再固定 <code>sleep 20</code>");
    expect(native).toContain("timing_barrier_intact=true");
    expect(native).toContain("Bash result，再观察到");
    expect(native).toContain("--preflight-only");
    expect(native).toContain("agentparty.claude-cross-session-native-preflight.v1");
    expect(native).toContain("model_calls_started=false");
    expect(native).toContain("不是 Claude 注册、原生送达");
    expect(native).toContain("error_code=invalid_arguments");
    expect(native).toContain("任何 Claude 探针前");
    expect(native).toContain("request|preflight|receiver_startup|execution|evidence|internal");
    expect(native).toContain("failure_phase=evidence");
    expect(native).not.toContain("必须先观察到 confirmed");
    expect(source.slice(integratedStart)).toContain("party_channel_peer_check");
    expect(source.slice(integratedStart)).toContain("<code>send_to</code>");
    expect(source.slice(integratedStart)).toContain("AgentParty 完整验收的所有非 help 结果使用 v2 acceptance schema");
    expect(source.slice(integratedStart)).toContain("model_calls_started=false");
    expect(source.slice(integratedStart)).toContain("delivery_verified=true");
    expect(source).toContain("同一把 consume lock");
    expect(read("web/public/docs/index.html")).toContain("shares the consume lock");
  });
});
